export enum ArticlesActionEnum {
  GET_ARTICLES = 'GET_ARTICLES',
  GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS',
}

export enum AuthActionEnum {
  SIGN_IN = 'SIGN_IN',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_FAIL = 'SIGN_IN_FAIL',
  SIGN_UP = 'SIGN_UP',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
}
