export { default as Header } from './Header/Header'
export { default as MainPage } from './MainPage/MainPage'
export { default as SignIn } from './SignIn/SignIn'
export { default as SignUp } from './SignUp/SignUp'
export { default as CommonButton } from './UI/CommonButton/CommonButton'
export { default as CommonInput } from './UI/CommonInput/CommonInput'
